# Generated by Django 4.2.6 on 2023-10-23 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0003_alter_astronomyshow_show_theme"),
    ]

    operations = [
        migrations.RenameField(
            model_name="astronomyshow",
            old_name="show_theme",
            new_name="show_themes",
        ),
    ]
