# Generated by Django 4.2.6 on 2023-10-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0004_rename_show_theme_astronomyshow_show_themes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="show_themes",
            field=models.ManyToManyField(
                blank=True, related_name="astronomy_shows", to="planetarium.showtheme"
            ),
        ),
    ]
